#pragma once

#define MINTPL_VERSION_MAJOR 1
#define MINTPL_VERSION_MINOR 2
#define MINTPL_VERSION_PATCH 0
#define _STRINGIZED(MAJ, MIN, PAT) #MAJ"."#MIN"."#PAT

#define MINTPL_VERSION _STRINGIZED(\
    MINTPL_VERSION_MAJOR,\
    MINTPL_VERSION_MINOR,\
    MINTPL_VERSION_PATCH\
)

